image: atlassian/default-image:2

pipelines:
  branches:
    main:
    - step:
        name: Build/Push Docker image
        image: python:3.9
        services:
        - docker
        script:
        - pip install awscli
        - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
        - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
        - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
        - COMMIT_HASH=$(git rev-parse --short HEAD) # Get the short commit hash
        - TAG_EPOCH=$(date +%s) # Generate epoch timestamp
        - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/adept_coalesce_connector:$TAG_EPOCH -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/adept_coalesce_connector:$COMMIT_HASH -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/adept_coalesce_connector:latest .
        - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/adept_coalesce_connector:$TAG_EPOCH
        - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/adept_coalesce_connector:$COMMIT_HASH
        - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/adept_coalesce_connector:latest
    - step:
    name: Linting
    image: python:3.9
    services:
    - docker
    script:
    - pip install flake8
    - flake8 --exclude=venv/*,env/*,base_old_datayml.py, preprocess_dataframe.py --max-line-length=120
